language: node_js
node_js:
  - "6"
  - "8"
  - "8.10"
  - "10"
before_install:
  - 'find lib -type f -name "package-lock.json" -delete'
before_script:
  - 'npm i -g serverless'
after_success: npm run coverage
